from _typeshed import Incomplete
from watchdog.events import PatternMatchingEventHandler

class FolderWatcher:
    def __init__(self, path, patterns=['*'], ignore_patterns=[]) -> None: ...
    def wait_for_event(self): ...
    def start(self) -> None: ...
    def produce(self): ...
    def stop(self) -> None: ...

class FolderEventHandler(PatternMatchingEventHandler):
    queue: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def on_created(self, event) -> None: ...
    def wait_for_event(self): ...
    def stop(self) -> None: ...
