from _typeshed import Incomplete
from arduino.app_bricks.cloud_llm import CloudLLM as CloudLLM, CloudModelProvider as CloudModelProvider
from arduino.app_bricks.cloud_llm.cloud_llm import DEFAULT_MEMORY as DEFAULT_MEMORY
from arduino.app_internal.core import get_brick_config as get_brick_config, get_brick_configured_model as get_brick_configured_model, resolve_address as resolve_address
from arduino.app_utils import Logger as Logger, brick as brick
from langchain_core.language_models import BaseChatModel as BaseChatModel
from typing import Any, Callable, Iterator

logger: Incomplete

class LargeLanguageModel(CloudLLM):
    """A Brick for interacting with locally-based Large Language Models (LLMs).

    This class wraps LangChain functionality to provide a simplified, unified interface
    for chatting with models like Qwenm, LLama, Gemma. It supports both synchronous
    'one-shot' responses and streaming output, with optional conversational memory.
    """
    GENIE_MODEL: str
    LLAMACPP_MODEL: str
    OLLAMA_MODEL: str
    def __init__(self, api_key: str = ..., system_prompt: str = '', temperature: float | None = 0.7, max_tokens: int = 512, timeout: int | None = None, tools: list[Callable[..., Any]] = None, model: str = None, **kwargs) -> None:
        '''Initializes the LargeLanguageModel brick with the specified provider and configuration.

        Args:
            api_key (str): The API access key for the target LLM service. Defaults to the
                \'LOCAL_LLM_API_KEY\' environment variable.
            model (str): The specific model name or identifier to use (e.g., "genie:qwen3-4b").
                If not provided, model will be determined from app configuration or default brick configuration.
            system_prompt (str): A system-level instruction that defines the AI\'s persona
                and constraints (e.g., "You are a helpful assistant"). Defaults to empty.
            temperature (Optional[float]): The sampling temperature between 0.0 and 1.0.
                Higher values make output more random/creative; lower values make it more
                deterministic. Defaults to 0.7.
            max_tokens (int): The maximum number of tokens to generate in the response.
                Defaults to 512.
            timeout (Optional[int]): The maximum duration in seconds to wait for a response before
                timing out. Defaults to None.
            tools (List[Callable[..., Any]]): A list of callable tool functions to register. Defaults to None.
            **kwargs: Additional arguments passed to the model constructor

        Raises:
            ValueError: If `api_key` is not provided (empty string).
        '''
    def list_models(self) -> list[str]:
        '''Returns a list of supported local model identifiers.

        Note: LargeLanguageModel supports OpenAI-compatible API. This method uses the OpenAI client to query available models from the local server.
        LangChain\'s OpenAI wrapper does not provide a direct method to list models, so we need to use the underlying OpenAI client directly.

        Returns:
            List[str]: A list of supported model names (e.g., ["qwen2.5-7b"]).
        '''
    def with_memory(self, max_messages: int = ...) -> LargeLanguageModel:
        """Enables conversational memory for this instance.

        Configures the Brick to retain a window of previous messages, allowing the
        AI to maintain context across multiple interactions.

        Args:
            max_messages (int): The maximum number of messages (user + AI) to keep
                in history. Older messages are discarded. Set to 0 to disable memory.
                Defaults to 10.

        Returns:
            LargeLanguageModel: The current instance, allowing for method chaining.
        """
    def get_client(self) -> BaseChatModel:
        """Returns the underlying LangChain model instance.

        This allows for advanced users to access the full capabilities of the model
        directly, such as calling `generate()` or `stream()` with custom message formats.

        Returns:
            BaseChatModel: The LangChain chat model instance used internally.
        """
    def chat(self, message: str, images: list[str | bytes] = None) -> str:
        """Sends a message to the AI and blocks until the complete response is received.

        This method automatically manages conversation history if memory is enabled.

        Args:
            message (str): The input text prompt from the user.
            images (List[str | bytes]): Optional list of image file paths or raw bytes to include in the prompt.

        Returns:
            str: The complete text response generated by the AI.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
        """
    def chat_stream(self, message: str, images: list[str | bytes] = None) -> Iterator[str]:
        """Sends a message to the AI and yields response tokens as they are generated.

        This allows for processing or displaying the response in real-time (streaming).
        The generation can be interrupted by calling `stop_stream()`.

        Args:
            message (str): The input text prompt from the user.
            images (List[str | bytes]): Optional list of image file paths or raw bytes to include in the prompt.

        Yields:
            str: Chunks of text (tokens) from the AI response.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
            AlreadyGenerating: If a streaming session is already active.
        """
    def stop_stream(self) -> None:
        """Signals the active streaming generation to stop.

        This sets an internal flag that causes the `chat_stream` iterator to break
        early. It has no effect if no stream is currently running.
        """
    def clear_memory(self) -> None:
        """Clears the conversational memory history.

        Resets the stored context. This is useful for starting a new conversation
        topic without previous context interfering. Only applies if memory is enabled.
        """
