from .memory import WindowedChatMessageHistory as WindowedChatMessageHistory
from .models import CloudModel as CloudModel, CloudModelProvider as CloudModelProvider
from .utils import logger as logger
from arduino.app_utils import brick as brick
from langchain_core.language_models import BaseChatModel as BaseChatModel
from langchain_core.messages import BaseMessage as BaseMessage, ToolCall as ToolCall
from typing import Any, Callable, Iterator

DEFAULT_MEMORY: int

class AlreadyGenerating(Exception):
    """Exception raised when a generation is already in progress."""

class CloudLLM:
    """A Brick for interacting with cloud-based Large Language Models (LLMs).

    This class wraps LangChain functionality to provide a simplified, unified interface
    for chatting with models like Claude, GPT, and Gemini. It supports both synchronous
    'one-shot' responses and streaming output, with optional conversational memory.
    """
    def __init__(self, api_key: str = ..., model: str | CloudModel = ..., system_prompt: str = '', temperature: float | None = 0.7, max_tool_loops: int = 8, timeout: int | None = None, tools: list[Callable[..., Any]] = None, callbacks: Any = None, **kwargs) -> None:
        '''Initializes the CloudLLM brick with the specified provider and configuration.

        Args:
            api_key (str): The API access key for the target LLM service. Defaults to the
                \'API_KEY\' environment variable.
            model (Union[str, CloudModel]): The model identifier. Accepts a `CloudModel`
                enum member (e.g., `CloudModel.OPENAI_GPT`) or its corresponding raw string
                value (e.g., `\'openai:gpt-5-mini\'`). Defaults to `CloudModel.ANTHROPIC_CLAUDE`.
                To identify the model provider, you need to use prefixes like \'openai:\', \'anthropic:\', or \'google:\'.
                If no prefix is provided, the model will be defaulted to an OpenAI compatible model.
            system_prompt (str): A system-level instruction that defines the AI\'s persona
                and constraints (e.g., "You are a helpful assistant"). Defaults to empty.
            temperature (Optional[float]): The sampling temperature between 0.0 and 1.0.
                Higher values make output more random/creative; lower values make it more
                deterministic. Defaults to 0.7.
            max_tool_loops (int): The maximum number of consecutive tool-call loops
                allowed during a single chat interaction. Defaults to 8.
            timeout (Optional[int]): The maximum duration in seconds to wait for a response before
                timing out. Defaults to None.
            callbacks (Any): Optional callbacks for monitoring generation events.
            tools (List[Callable[..., Any]]): A list of callable tool functions to register. Defaults to None.
            **kwargs: Additional arguments passed to the model constructor

        Raises:
            ValueError: If `api_key` is not provided (empty string).
        '''
    def with_memory(self, max_messages: int = ...) -> CloudLLM:
        """Enables conversational memory for this instance.

        Configures the Brick to retain a window of previous messages, allowing the
        AI to maintain context across multiple interactions.

        Args:
            max_messages (int): The maximum number of messages (user + AI) to keep
                in history. Older messages are discarded. Set to 0 to disable memory.
                Defaults to 10.

        Returns:
            CloudLLM: The current instance, allowing for method chaining.
        """
    def get_client(self) -> BaseChatModel:
        """Returns the underlying LangChain model instance.

        This allows for advanced users to access the full capabilities of the model
        directly, such as calling `generate()` or `stream()` with custom message formats.

        Returns:
            BaseChatModel: The LangChain chat model instance used internally.
        """
    def chat(self, message: str, images: list[str | bytes] = None) -> str:
        """Sends a message to the AI and blocks until the complete response is received.

        This method automatically manages conversation history if memory is enabled.

        Args:
            message (str): The input text prompt from the user.
            images (List[str | bytes]): Optional list of image file paths or raw bytes to include in the prompt.

        Returns:
            str: The complete text response generated by the AI.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
        """
    def chat_stream(self, message: str, images: list[str | bytes] = None) -> Iterator[str]:
        """Sends a message to the AI and yields response tokens as they are generated.

        This allows for processing or displaying the response in real-time (streaming).
        The generation can be interrupted by calling `stop_stream()`.

        Args:
            message (str): The input text prompt from the user.
            images (List[str | bytes]): Optional list of image file paths or raw bytes to include in the prompt.

        Yields:
            str: Chunks of text (tokens) from the AI response.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
            AlreadyGenerating: If a streaming session is already active.
        """
    def stop_stream(self) -> None:
        """Signals the active streaming generation to stop.

        This sets an internal flag that causes the `chat_stream` iterator to break
        early. It has no effect if no stream is currently running.
        """
    def clear_memory(self) -> None:
        """Clears the conversational memory history.

        Resets the stored context. This is useful for starting a new conversation
        topic without previous context interfering. Only applies if memory is enabled.
        """

def model_factory(model_name: CloudModel, **kwargs) -> BaseChatModel:
    """Factory function to instantiate the specific LangChain chat model.

    This function maps the supported `CloudModel` enum values to their respective
    LangChain implementations. In case of prefix-based model identifiers (e.g., 'openai:gpt-5-mini'),
    it extracts the provider and model name accordingly.

    Args:
        model_name (CloudModel): The enum or string identifier for the model.
            Model name can include provider prefixes like 'openai:', 'anthropic:', or 'google:'
            to specify the provider. If no prefix is provided, the model will be defaulted to an OpenAI compatible model.
        **kwargs: Additional arguments passed to the model constructor (e.g., api_key, temperature).

    Returns:
        BaseChatModel: An instance of a LangChain chat model wrapper.

    Raises:
        ValueError: If `model_name` does not match one of the supported options.
    """
