import { spawn } from "node:child_process";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as vscode from "vscode";
import type { AppInfo } from "./api/types";

/**
 * Fast Reload — make saved Python edits take effect without a full app restart.
 *
 * App Lab runs the Python half as `python main.py` inside a container, and that
 * process does not reload its own source. The cheap fix is a SIGHUP handler that
 * re-execs the interpreter; the app folder is bind-mounted into the container, so
 * the re-exec picks up the edited files instantly — no re-provisioning, no
 * `docker compose up`.
 *
 * We inject the handler non-invasively via a `sitecustomize.py` that Python
 * auto-imports at startup. It must live on `PYTHONPATH`: `run.sh` adds
 * `<app>/bricks` to `PYTHONPATH` (when that dir exists), and — verified
 * empirically — a `sitecustomize` on `PYTHONPATH` is auto-imported whereas one in
 * the script directory is not. So the file goes in `<app>/bricks/sitecustomize.py`.
 *
 * On save we resolve the app's main container by the labels the daemon stamps
 * (`cc.arduino.app.main=true` + `cc.arduino.app.path=<app path>`) and send it
 * SIGHUP over the local Docker socket — no daemon round-trip.
 */

/** Marker identifying our generated file, so we never clobber a user's own. */
const SENTINEL = "arduino-app-cli:fast-reload";

const RELATIVE_FILE = path.join("bricks", "sitecustomize.py");

/** workspaceState key holding the app dirs we've injected into (for cleanup). */
const STATE_KEY = "fastReload.injectedDirs";

const SITECUSTOMIZE = `# ${SENTINEL} — auto-generated by the Arduino App Lab VS Code extension.
#
# Installs a SIGHUP handler that re-execs the app process so saved Python changes
# are picked up WITHOUT a full app restart (no re-provisioning). This file sits on
# PYTHONPATH (run.sh adds <app>/bricks), so it is imported automatically at
# interpreter startup. Safe to delete: the extension recreates it while Fast
# Reload is enabled and removes it when disabled.
import os
import signal
import sys


def _arduino_applab_fast_reload(*_args):
    os.execv(sys.executable, [sys.executable, *sys.argv])


try:
    signal.signal(signal.SIGHUP, _arduino_applab_fast_reload)
except (ValueError, OSError):
    # signal.signal only works on the main thread of the main interpreter; if
    # that's not the case here, fast reload simply stays unavailable.
    pass
`;

export interface FastReloadDeps {
  output: vscode.OutputChannel;
  /** The app owning the active editor, if any. */
  activeApp: () => AppInfo | undefined;
  /** Resolve an app's on-disk folder (the list endpoint omits `path`). */
  resolveAppDir: (app: AppInfo) => Promise<string | undefined>;
}

export class FastReloadManager implements vscode.Disposable {
  private subs: vscode.Disposable[] = [];
  /** Warned-once flags so a missing `docker` / user-owned file isn't spammy. */
  private warnedDockerMissing = false;

  constructor(
    private readonly ctx: vscode.ExtensionContext,
    private readonly deps: FastReloadDeps,
  ) {
    this.subs.push(
      // One long-lived save listener; it no-ops while disabled (cheap).
      vscode.workspace.onDidSaveTextDocument((doc) => void this.onSave(doc)),
      vscode.workspace.onDidChangeConfiguration((e) => {
        if (e.affectsConfiguration("appLab.python.fastReload")) {
          void this.onEnablementChanged();
        }
      }),
    );
    if (this.enabled) {
      void this.ensureForActiveApp();
    }
  }

  dispose(): void {
    for (const s of this.subs) {
      s.dispose();
    }
  }

  private get enabled(): boolean {
    return vscode.workspace.getConfiguration("appLab").get<boolean>("python.fastReload", false);
  }

  /** Flip the setting; {@link onEnablementChanged} reacts to the change. */
  async toggle(): Promise<void> {
    const next = !this.enabled;
    const target = vscode.workspace.workspaceFolders?.length
      ? vscode.ConfigurationTarget.Workspace
      : vscode.ConfigurationTarget.Global;
    await vscode.workspace.getConfiguration("appLab").update("python.fastReload", next, target);
    vscode.window.showInformationMessage(
      next
        ? vscode.l10n.t(
            "Fast Reload enabled. Start (or restart) the app once so the reload handler loads; after that, saving a Python file reloads it.",
          )
        : vscode.l10n.t("Fast Reload disabled."),
    );
  }

  /** Active editor changed app: keep the injected file in step when enabled. */
  onActiveAppChanged(): void {
    if (this.enabled) {
      void this.ensureForActiveApp();
    }
  }

  private async onEnablementChanged(): Promise<void> {
    if (this.enabled) {
      await this.ensureForActiveApp();
    } else {
      await this.cleanupAll();
    }
  }

  private async onSave(doc: vscode.TextDocument): Promise<void> {
    if (!this.enabled) {
      return;
    }
    if (doc.languageId !== "python" && !doc.uri.fsPath.endsWith(".py")) {
      return;
    }
    const app = this.deps.activeApp();
    if (!app) {
      return;
    }
    const dir = await this.deps.resolveAppDir(app);
    if (!dir || !isInside(dir, doc.uri.fsPath)) {
      return;
    }
    // Make sure the handler is installed for next start, then reload now.
    await this.ensureFor(dir);
    await this.reload(app, dir);
  }

  private async ensureForActiveApp(): Promise<void> {
    const app = this.deps.activeApp();
    if (!app) {
      return;
    }
    const dir = await this.deps.resolveAppDir(app);
    if (dir) {
      await this.ensureFor(dir);
    }
  }

  /** Write `<dir>/bricks/sitecustomize.py`, unless a non-ours file is there. */
  private async ensureFor(dir: string): Promise<void> {
    const file = path.join(dir, RELATIVE_FILE);
    try {
      const existing = await fs.readFile(file, "utf8").catch(() => undefined);
      if (existing !== undefined && !existing.includes(SENTINEL)) {
        vscode.window.showWarningMessage(
          vscode.l10n.t(
            "Fast Reload: {0} already exists and wasn't created by the extension — leaving it untouched.",
            file,
          ),
        );
        return;
      }
      if (existing === SITECUSTOMIZE) {
        await this.remember(dir);
        return;
      }
      await fs.mkdir(path.dirname(file), { recursive: true });
      await fs.writeFile(file, SITECUSTOMIZE, "utf8");
      await this.remember(dir);
      this.deps.output.appendLine(`[fast-reload] wrote ${file}`);
    } catch (err) {
      this.deps.output.appendLine(`[fast-reload] could not write ${file}: ${asMessage(err)}`);
    }
  }

  /** Remove every file we injected (sentinel-checked) and forget them. */
  private async cleanupAll(): Promise<void> {
    const dirs = this.injectedDirs();
    for (const dir of dirs) {
      const file = path.join(dir, RELATIVE_FILE);
      try {
        const existing = await fs.readFile(file, "utf8").catch(() => undefined);
        if (existing !== undefined && existing.includes(SENTINEL)) {
          await fs.rm(file);
          this.deps.output.appendLine(`[fast-reload] removed ${file}`);
        }
      } catch (err) {
        this.deps.output.appendLine(`[fast-reload] could not remove ${file}: ${asMessage(err)}`);
      }
    }
    await this.ctx.workspaceState.update(STATE_KEY, []);
  }

  /** Find the app's running main container and send it SIGHUP. */
  private async reload(app: AppInfo, dir: string): Promise<void> {
    let ids: string[];
    try {
      const out = await docker([
        "ps",
        "-q",
        "--filter",
        "label=cc.arduino.app.main=true",
        "--filter",
        `label=cc.arduino.app.path=${dir}`,
      ]);
      ids = out.split("\n").map((s) => s.trim()).filter(Boolean);
    } catch (err) {
      this.warnDockerOnce(err);
      return;
    }
    if (ids.length === 0) {
      // Not running (or never started since enabling) — nothing to signal.
      this.deps.output.appendLine(`[fast-reload] ${app.name}: no running container; skipped`);
      vscode.window.showWarningMessage(
        vscode.l10n.t(
          "Fast Reload: {0} isn't running, so there was nothing to reload. Start the app first.",
          app.name,
        ),
      );
      return;
    }
    let failure: string | undefined;
    for (const id of ids) {
      try {
        await docker(["kill", "-s", "HUP", id]);
        this.deps.output.appendLine(`[fast-reload] ${app.name}: reloaded (SIGHUP ${id.slice(0, 12)})`);
      } catch (err) {
        failure = asMessage(err);
        this.deps.output.appendLine(`[fast-reload] ${app.name}: SIGHUP failed: ${failure}`);
      }
    }
    if (failure === undefined) {
      vscode.window.showInformationMessage(
        vscode.l10n.t("Fast Reload: {0} reloaded.", app.name),
      );
    } else {
      vscode.window.showErrorMessage(
        vscode.l10n.t("Fast Reload: {0} couldn't be reloaded — {1}", app.name, failure),
      );
    }
  }

  private warnDockerOnce(err: unknown): void {
    this.deps.output.appendLine(`[fast-reload] docker unavailable: ${asMessage(err)}`);
    if (!this.warnedDockerMissing) {
      this.warnedDockerMissing = true;
      vscode.window.showWarningMessage(
        vscode.l10n.t(
          "Fast Reload couldn't reach Docker. It works when VS Code runs on the board (e.g. via Remote-SSH), where the app's container lives.",
        ),
      );
    }
  }

  private injectedDirs(): string[] {
    return this.ctx.workspaceState.get<string[]>(STATE_KEY, []);
  }

  private async remember(dir: string): Promise<void> {
    const dirs = this.injectedDirs();
    if (!dirs.includes(dir)) {
      await this.ctx.workspaceState.update(STATE_KEY, [...dirs, dir]);
    }
  }
}

/** True when `file` is at or below `dir`. */
function isInside(dir: string, file: string): boolean {
  const rel = path.relative(dir, file);
  return rel !== "" && !rel.startsWith("..") && !path.isAbsolute(rel);
}

/** Run `docker <args>` once and resolve stdout (rejects on non-zero exit). */
function docker(args: string[]): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    const proc = spawn("docker", args, { stdio: ["ignore", "pipe", "pipe"] });
    let out = "";
    let err = "";
    proc.stdout.on("data", (c: Buffer) => (out += c.toString()));
    proc.stderr.on("data", (c: Buffer) => (err += c.toString()));
    proc.on("error", reject);
    proc.on("close", (code) =>
      code === 0 ? resolve(out) : reject(new Error(err.trim() || `docker exited with code ${code}`)),
    );
  });
}

function asMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}
